repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      # Run the linter.
      # - id: ruff
      #   args: [--fix, backend]
      # Run the formatter.
      - id: ruff-format
        args: [backend]
        exclude: (migrations)
  - repo: local
    hooks:
      - id: format-frontend
        name: format-frontend
        files: ^frontend/.$
        language: system
        entry: sh -c "npm run format --prefix frontend"
