[tool.poetry]
name = "ciso-assistant-community"
version = "0.1.0"
description = ""
authors = ["intuitem <contact@intuitem.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1"
weasyprint = "62.3"
psycopg2-binary = "2.9.9"
gunicorn = "22.0.0"
django-filter = "24.3"
whitenoise = "6.7.0"
argon2-cffi = "23.1.0"
djangorestframework = "3.15.2"
django-tailwind = "3.8.0"
pyyaml = "6.0.2"
django-structlog = "8.1.0"
structlog = "24.4.0"
python-dotenv = "1.0.1"
drf-spectacular = "0.27.2"
django-rest-knox = "5.0.1"
django-allauth = { version = "64.0.0", extras = ["socialaccount", "saml"] }
python3-saml = "^1.16"
requests = "^2"
python-magic = "^0.4.27"

[tool.poetry.group.dev.dependencies]
pytest-django = "4.8.0"
pytest-html = "4.1.1"
django-stubs = "5.0.2"
coverage = "7.5.4"
pre-commit = "3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
