[tool.poetry]
name = "enterprise_core"
version = "0.1.0"
description = ""
authors = ["intuitem <contact@intuitem.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
