name: Build and Push Docker Images Dummy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  UBUNTU_VERSION: "ubuntu-24.04"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all history and tags are fetched

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get version and Create .meta file
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "BUILD=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

          echo "CISO_ASSISTANT_VERSION=$(git describe --tags --always)" > .meta
          echo "CISO_ASSISTANT_BUILD=$(git rev-parse --short HEAD)" >> .meta

          cp .meta ./backend/
          cp .meta ./backend/ciso_assistant/

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
